In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
pd.options.mode.chained_assignment = None
df = pd.read_csv('USD-JPY train set.csv',parse_dates = True)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE_TIME      1200 non-null   object
 1   HIGH           1200 non-null   float64
 2   LOW            1200 non-null   float64
 3   OPEN           1200 non-null   float64
 4   CLOSE          1200 non-null   float64
 5   Event_value    1200 non-null   float64
 6   Event_type     1200 non-null   object
 7   Time duration  1200 non-null   object
 8   Trend          1200 non-null   object
 9   Boundaries     1200 non-null   float64
 10  strength       1200 non-null   float64
 11  time           1200 non-null   object
dtypes: float64(7), object(5)
memory usage: 112.6+ KB

In [4]:
df['DATE_TIME']= pd.to_datetime(df['DATE_TIME'])
df['strength'] = pd.to_numeric(df['strength'])
df.head()

,DATE_TIME,HIGH,LOW,OPEN,CLOSE,Event_value,Event_type,Time duration,Trend,Boundaries,strength,time
0,2011-01-13 08:30:00,82.841,82.728,82.732,82.818,1.10,USD_PPI,Short term,RANGE,0.01290,0.041149,8:30:00
1,2011-01-24 22:30:00,82.483,82.437,82.483,82.445,0.10,JPY_IR,Long term,RANGE,0.01085,0.045159,22:30:00
2,2011-01-26 14:15:00,82.425,82.323,82.388,82.326,0.25,USD_IR,Short term,RANGE,0.04680,0.067677,14:15:00
3,2011-01-28 08:30:00,82.387,82.298,82.385,82.298,3.20,USD_GDP,Short term,RANGE,0.01700,0.053575,8:30:00
4,2011-02-15 08:30:00,83.843,83.773,83.781,83.788,0.30,USD_RETAIL,Long term,UP,0.00990,0.044591,8:30:00

In [5]:
#event values replacing function, RANGE = 1 ,DOWN= 0, UP =2
def trend_encoding(df):
    le = LabelEncoder()
    df['Trend'] = le.fit_transform(df['Trend'])
    return df

In [6]:
df = trend_encoding(df)
#EVENT wise results view
def event_results(df) :
    new_df = df[df['Trend']==1]
    range_results = new_df.groupby('Event_type').mean()
    range_results = range_results['strength']
    print('(1) Fair result for the strength in each event, when the trend is in range : ')
    print('------------------------------------------------------------------------')
    print(range_results)
    r_1 = pd.DataFrame(range_results)
    
    new_df= df[df['Trend']==0]
    range_results = new_df.groupby('Event_type').mean()
    range_results = range_results['strength']
    print('(2) Fair result for the strength in each event, when the trend goes DOWN : ')
    print('------------------------------------------------------------------------')
    print(range_results)
    r_2 = pd.DataFrame(range_results)
    
    new_df = df[df['Trend']==2]
    range_results = new_df.groupby('Event_type').mean()
    range_results = range_results['strength']
    print('(3) Fair result for the strength in each event, when the trend goes UP : ')
    print('------------------------------------------------------------------------')
    print(range_results)
    r_3 = pd.DataFrame(range_results)
    return r_1,r_2,r_3
    
df

,DATE_TIME,HIGH,LOW,OPEN,CLOSE,Event_value,Event_type,Time duration,Trend,Boundaries,strength,time
0,2011-01-13 08:30:00,82.841,82.728,82.732,82.818,1.10,USD_PPI,Short term,1,0.01290,0.041149,8:30:00
1,2011-01-24 22:30:00,82.483,82.437,82.483,82.445,0.10,JPY_IR,Long term,1,0.01085,0.045159,22:30:00
2,2011-01-26 14:15:00,82.425,82.323,82.388,82.326,0.25,USD_IR,Short term,1,0.04680,0.067677,14:15:00
3,2011-01-28 08:30:00,82.387,82.298,82.385,82.298,3.20,USD_GDP,Short term,1,0.01700,0.053575,8:30:00
4,2011-02-15 08:30:00,83.843,83.773,83.781,83.788,0.30,USD_RETAIL,Long term,2,0.00990,0.044591,8:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2019-12-11 14:00:00,108.769,108.615,108.681,108.621,1.75,USD_IR,Long term,0,0.01555,-0.043318,14:00:00
1196,2019-12-12 08:30:00,108.617,108.558,108.617,108.597,0.00,USD_PPI,Long term,2,0.01555,0.048136,8:30:00
1197,2019-12-13 08:30:00,109.622,109.493,109.544,109.585,0.20,USD_RETAIL,Short term,0,0.01555,-0.058409,8:30:00
1198,2019-12-18 22:00:00,109.585,109.559,109.572,109.562,-0.10,JPY_IR,Long term,1,0.00635,0.045159,22:00:00
1199,2019-12-19 18:30:00,109.401,109.364,109.364,109.373,0.50,JPY_CPI,Long term,0,0.00635,-0.022045,18:30:00

In [7]:
r_1,r_2,r_3 = event_results(df)

(1) Fair result for the strength in each event, when the trend is in range :
------------------------------------------------------------------------
Event_type
JPY_CPI       0.034474
JPY_IR        0.045159
JPY_UNEMP     0.031687
USD_CPI       0.056074
USD_GDP       0.053575
USD_IR        0.067677
USD_PPI       0.041149
USD_RETAIL    0.052260
Name: strength, dtype: float64
(2) Fair result for the strength in each event, when the trend goes DOWN :
------------------------------------------------------------------------
Event_type
JPY_CPI      -0.057633
JPY_IR       -0.069354
JPY_UNEMP    -0.037379
USD_CPI      -0.051963
USD_GDP      -0.052716
USD_IR       -0.078611
USD_PPI      -0.046155
USD_RETAIL   -0.051194
Name: strength, dtype: float64
(3) Fair result for the strength in each event, when the trend goes UP :
------------------------------------------------------------------------
Event_type
JPY_CPI       0.037391
JPY_IR        0.051231
JPY_UNEMP     0.042628
USD_CPI       0.067674
USD_GDP       0.049583
USD_IR        0.098510
USD_PPI       0.059859
USD_RETAIL    0.061894
Name: strength, dtype: float64

In [8]:
#0-long 1-Short IR/CPI
le = LabelEncoder()
df['Time duration'] = le.fit_transform(df['Time duration'])   
def event_duration(df):
    new_df = df.groupby(['Event_type'])['Time duration'].agg(lambda x:x.value_counts().index[0])
    return new_df

In [9]:
new_df = event_duration(df)
new_df

Event_type
JPY_CPI       0
JPY_IR        0
JPY_UNEMP     0
USD_CPI       0
USD_GDP       0
USD_IR        0
USD_PPI       0
USD_RETAIL    0
Name: Time duration, dtype: int32

In [10]:
r_1 = r_1 .reset_index()
r_1

   Event_type  strength
0     JPY_CPI  0.034474
1      JPY_IR  0.045159
2   JPY_UNEMP  0.031687
3     USD_CPI  0.056074
4     USD_GDP  0.053575
5      USD_IR  0.067677
6     USD_PPI  0.041149
7  USD_RETAIL  0.052260

In [11]:
output = r_1.merge(r_2, on ='Event_type',suffixes = ['_range','_down'],how ='left')\
            .merge(r_3, on ='Event_type',how ='left')

In [12]:
output['strength_up'] = output['strength'] 
output = output .drop(columns=['strength'],axis = 1)
output

   Event_type  strength_range  strength_down  strength_up
0     JPY_CPI        0.034474      -0.057633     0.037391
1      JPY_IR        0.045159      -0.069354     0.051231
2   JPY_UNEMP        0.031687      -0.037379     0.042628
3     USD_CPI        0.056074      -0.051963     0.067674
4     USD_GDP        0.053575      -0.052716     0.049583
5      USD_IR        0.067677      -0.078611     0.098510
6     USD_PPI        0.041149      -0.046155     0.059859
7  USD_RETAIL        0.052260      -0.051194     0.061894

In [13]:
new_df   = pd.DataFrame(new_df)
new_df = new_df.reset_index()
output = output.merge(new_df, on = 'Event_type')
output

   Event_type  strength_range  strength_down  strength_up  Time duration
0     JPY_CPI        0.034474      -0.057633     0.037391              0
1      JPY_IR        0.045159      -0.069354     0.051231              0
2   JPY_UNEMP        0.031687      -0.037379     0.042628              0
3     USD_CPI        0.056074      -0.051963     0.067674              0
4     USD_GDP        0.053575      -0.052716     0.049583              0
5      USD_IR        0.067677      -0.078611     0.098510              0
6     USD_PPI        0.041149      -0.046155     0.059859              0
7  USD_RETAIL        0.052260      -0.051194     0.061894              0

In [14]:
output.to_csv('Final results of USD-JPY.csv',index = False)