In [55]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from datetime import datetime,timedelta
import datetime

In [56]:
#IMPORT ALL THE FILES AND KEEP ONLY DESIRERED COLUMNS OF THE EVENT DATA

col = ['DATE','TIME','c','D','E','F','G','AUD_GDP','I','J']
drop_cols = ['c','D','E','F','G','I','J']

AUD_USD_df = pd.read_csv('AUDUSD-2000-2020-15m.csv') #AUS_USD CURRENCY DATA SET

# import all the event files, variable name tells what is the event
#use 'parse_dates' keyword ynside the 'read_csv' function in order to combine date and time also convert the data type into 'datetime64'
AUD_GDP_df = pd.read_csv('AUD_GDP.csv',header = None,names =['DATE','TIME','c','D','E','F','G','AUD_GDP','I','J'] ,parse_dates= [[0,1]]) 
AUD_GDP_df = AUD_GDP_df.drop(columns=drop_cols)

AUD_PPI_df = pd.read_csv('AUD_PPI.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','AUD_PPI','I','J'],parse_dates= [[0,1]])
AUD_PPI_df = AUD_PPI_df.drop(columns=drop_cols)

AUD_RETAILSALES_df = pd.read_csv('AUD_RETAILSALES.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','AUD_RETAILSALES','I','J'],parse_dates= [[0,1]])
AUD_RETAILSALES_df = AUD_RETAILSALES_df.drop(columns=drop_cols)

AUD_UNEMP_df = pd.read_csv('AUD_UNEMP.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','AUD_UNEMP','I','J'],parse_dates= [[0,1]])
AUD_UNEMP_df = AUD_UNEMP_df.drop(columns=drop_cols)

AUD_CPI_df = pd.read_csv('AUD_CPI.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','AUD_CPI','I','J'],parse_dates= [[0,1]])
AUD_CPI_df = AUD_CPI_df.drop(columns=drop_cols)

USD_CPI_df = pd.read_csv('USD_CPI.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','USD_CPI','I','J'],parse_dates= [[0,1]])
USD_CPI_df = USD_CPI_df.drop(columns=drop_cols)

USD_GDP_df = pd.read_csv('USD_GDP.csv',header = None,names =['DATE','TIME','c','D','E','F','G','USD_GDP','I','J'],parse_dates= [[0,1]])
USD_GDP_df = USD_GDP_df.drop(columns=drop_cols)

USD_IR_df = pd.read_csv('USD_IR.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','USD_IR','I','J'],parse_dates= [[0,1]])
USD_IR_df = USD_IR_df.drop(columns=drop_cols)

USD_PAYROLL_df = pd.read_csv('USD_PAYROLL.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','USD_PAYROLL','I','J'],parse_dates= [[0,1]])
USD_PAYROLL_df = USD_PAYROLL_df.drop(columns=drop_cols)

USD_PPI_df = pd.read_csv('USD_PPI.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','USD_PPI','I','J'],parse_dates= [[0,1]])
USD_PPI_df = USD_PPI_df.drop(columns=drop_cols)

USD_RETAIL_df = pd.read_csv('USD_RETAIL.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','USD_RETAIL','I','J'],parse_dates= [[0,1]])
USD_RETAIL_df = USD_RETAIL_df.drop(columns=drop_cols)

USD_UNEMP_df = pd.read_csv('USD_UNEMP.csv',header = None,names = ['DATE','TIME','c','D','E','F','G','USD_UNEMP','I','J'],parse_dates= [[0,1]])
USD_UNEMP_df = USD_UNEMP_df.drop(columns=drop_cols)

In [57]:
#select the data from 2011-2020 from the 'AUD_USD_df' data set where the pips are located.

d =AUD_USD_df.loc[272143:500027 ,:]
df = d.reset_index(drop=True)
df['DATE_TIME'] = pd.to_datetime(df['DATE_TIME'])
df['DATE_TIME'] = df['DATE_TIME']-pd.Timedelta(hours=7)

pd.options.mode.chained_assignment = None  #  not important codeline. This is for avoiding the warning of chained assignments


#merge all the dataframes (all the events of both countries and market prices by matching with the date and time values)

new_df =  df.merge(AUD_GDP_df, on = 'DATE_TIME', how = 'left')\
          .merge(AUD_PPI_df, on = 'DATE_TIME', how = 'left')\
            .merge(AUD_RETAILSALES_df, on = 'DATE_TIME', how = 'left')\
            .merge(AUD_UNEMP_df, on = 'DATE_TIME', how = 'left')\
            .merge(AUD_CPI_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_PPI_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_CPI_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_GDP_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_IR_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_PAYROLL_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_RETAIL_df, on = 'DATE_TIME', how = 'left')\
            .merge(USD_UNEMP_df, on = 'DATE_TIME', how = 'left')
            
#checking whether is there any overlapping events in the merged dataframe

temp_df = new_df.drop(columns = ['DATE_TIME','HIGH','LOW','OPEN','CLOSE']).notnull().sum(axis=1) # A Series of counting number of non 'nan' values accross a row

#A function to checking number of overlap events

def OverlapCounter(t_df):
    count = 0
    for i in t_df:
        if i>1:
            count+=1
    print('There are ', count, ' overlapping events')
    

print(OverlapCounter(temp_df)) # count overlap events

t_df = new_df[temp_df==1]   #filter and make a new datframe that combining all the non overlapping events

df_with_reset_index = t_df.reset_index(drop=True)
df_with_reset_index

There are  187  overlapping events
None

,DATE_TIME,HIGH,LOW,OPEN,CLOSE,AUD_GDP,AUD_PPI,AUD_RETAILSALES,AUD_UNEMP,AUD_CPI,USD_PPI,USD_CPI,USD_GDP,USD_IR,USD_PAYROLL,USD_RETAIL,USD_UNEMP
0,2011-01-09 19:30:00,0.99716,0.99661,0.99712,0.99704,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-01-12 19:30:00,0.99665,0.99451,0.99451,0.99586,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-01-13 08:30:00,1.00054,0.99878,1.00051,0.99919,NaN,NaN,NaN,NaN,NaN,1.1,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-01-23 19:30:00,0.98839,0.98720,0.98730,0.98721,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011-01-24 19:30:00,0.99443,0.99380,0.99386,0.99406,NaN,NaN,NaN,NaN,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,2020-03-11 08:30:00,0.65333,0.65208,0.65278,0.65218,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,NaN,NaN
761,2020-03-12 08:30:00,0.63489,0.63363,0.63429,0.63465,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,NaN,NaN,NaN,NaN
762,2020-03-15 17:00:00,0.62280,0.61757,0.62260,0.61761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,NaN,NaN
763,2020-03-17 08:30:00,0.60382,0.60131,0.60150,0.60184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,NaN
764,2020-03-18 20:30:00,0.56977,0.56492,0.56886,0.56580,NaN,NaN,NaN,5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
# create two new columns. One column including the type of the event while the other consisiting with the relevant event value

x= df_with_reset_index.drop(columns = ['DATE_TIME','HIGH','LOW','OPEN','CLOSE'])

event_type = []
event_values=[]
for i in range(len(x)):
    for col in x.columns:
        val = x.loc[i,col]
        if str(val) != 'nan':
            event_type.append(col)
            
            event_values.append(val)
            
df_with_reset_index['Event_value'] = event_values
df_with_reset_index['Event_type'] = event_type
        
df_with_reset_index

,DATE_TIME,HIGH,LOW,OPEN,CLOSE,AUD_GDP,AUD_PPI,AUD_RETAILSALES,AUD_UNEMP,AUD_CPI,USD_PPI,USD_CPI,USD_GDP,USD_IR,USD_PAYROLL,USD_RETAIL,USD_UNEMP,Event_value,Event_type
0,2011-01-09 19:30:00,0.99716,0.99661,0.99712,0.99704,NaN,NaN,0.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.30,AUD_RETAILSALES
1,2011-01-12 19:30:00,0.99665,0.99451,0.99451,0.99586,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,AUD_UNEMP
2,2011-01-13 08:30:00,1.00054,0.99878,1.00051,0.99919,NaN,NaN,NaN,NaN,NaN,1.1,NaN,NaN,NaN,NaN,NaN,NaN,1.10,USD_PPI
3,2011-01-23 19:30:00,0.98839,0.98720,0.98730,0.98721,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.10,AUD_PPI
4,2011-01-24 19:30:00,0.99443,0.99380,0.99386,0.99406,NaN,NaN,NaN,NaN,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.40,AUD_CPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,2020-03-11 08:30:00,0.65333,0.65208,0.65278,0.65218,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,NaN,NaN,0.20,USD_CPI
761,2020-03-12 08:30:00,0.63489,0.63363,0.63429,0.63465,NaN,NaN,NaN,NaN,NaN,-0.6,NaN,NaN,NaN,NaN,NaN,NaN,-0.60,USD_PPI
762,2020-03-15 17:00:00,0.62280,0.61757,0.62260,0.61761,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25,NaN,NaN,NaN,0.25,USD_IR
763,2020-03-17 08:30:00,0.60382,0.60131,0.60150,0.60184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.5,NaN,-0.50,USD_RETAIL
764,2020-03-18 20:30:00,0.56977,0.56492,0.56886,0.56580,NaN,NaN,NaN,5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.10,AUD_UNEMP

In [64]:
# rearrange the data frame by keeping only desired columns
train_df = df_with_reset_index[['DATE_TIME','HIGH', 'LOW','OPEN','CLOSE','Event_value','Event_type']]



AUD_USD_df['DATE_TIME'] = pd.to_datetime(AUD_USD_df['DATE_TIME']) #convert to datetime object


for i in range(8):  
    tempor_df = pd.DataFrame({}) # created a temporary dataframe in order to store shifted dates

    tempor_df['DATE_TIME'] = train_df['DATE_TIME'] + pd.Timedelta(minutes=15*(i+1)) #shift the time by 15 minutes of slicers  

    x = pd.merge(AUD_USD_df[['DATE_TIME','HIGH','LOW','OPEN','CLOSE']],tempor_df, how='right', on='DATE_TIME') # merge the shifted date column and join HIGH, LOW values in the pip data set 

    x_1 = x['HIGH'].fillna(method = 'bfill') # missing 'nan' values with the next value respected to the 'nan'
    x_2 = x['LOW'].fillna(method= 'bfill')
    x_3 = x['CLOSE'].fillna(method = 'bfill')
    x_4 = x['OPEN'].fillna(method = 'bfill')
    
    col_name = 'average_value_after_'+ str(15*(i+1)) + '_mins'
    
    train_df[col_name] = (x_1 + x_2 + x_3 + x_4)/4
    
for i in range(8):
    col_name = 'average_from_' + str((i+1)*15) + '_to_' + str((i+2)*15)
    train_df[col_name_] = train_df.iloc[:,i+8] - train_df.iloc[:i+7]

,DATE_TIME,HIGH,LOW,OPEN,CLOSE,Event_value,Event_type,average_value_after_15_mins,average_value_after_30_mins,average_value_after_45_mins,average_value_after_60_mins,average_value_after_75_mins,average_value_after_90_mins,average_value_after_105_mins,average_value_after_120_mins
0,2011-01-09 19:30:00,0.99716,0.99661,0.99712,0.99704,0.30,AUD_RETAILSALES,0.995855,0.995183,0.994450,0.995255,0.995985,0.995685,0.995080,0.994792
1,2011-01-12 19:30:00,0.99665,0.99451,0.99451,0.99586,5.00,AUD_UNEMP,0.995855,0.995183,0.994450,0.995255,0.995985,0.995685,0.995080,0.994792
2,2011-01-13 08:30:00,1.00054,0.99878,1.00051,0.99919,1.10,USD_PPI,0.995248,0.994782,0.994103,0.993792,0.994528,0.995192,0.996082,0.996595
3,2011-01-23 19:30:00,0.98839,0.98720,0.98730,0.98721,0.10,AUD_PPI,0.999523,0.999280,0.999055,0.998835,0.998393,0.998200,0.997742,0.997465
4,2011-01-24 19:30:00,0.99443,0.99380,0.99386,0.99406,0.40,AUD_CPI,0.999523,0.999280,0.999055,0.998835,0.998393,0.998200,0.997742,0.997465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,2020-03-11 08:30:00,0.65333,0.65208,0.65278,0.65218,0.20,USD_CPI,0.650190,0.650273,0.650748,0.651725,0.652072,0.652118,0.652048,0.652317
761,2020-03-12 08:30:00,0.63489,0.63363,0.63429,0.63465,-0.60,USD_PPI,0.643855,0.644585,0.644810,0.644695,0.644942,0.645340,0.645443,0.644855
762,2020-03-15 17:00:00,0.62280,0.61757,0.62260,0.61761,0.25,USD_IR,0.607665,0.607838,0.608145,0.608005,0.608362,0.608720,0.608510,0.608130
763,2020-03-17 08:30:00,0.60382,0.60131,0.60150,0.60184,-0.50,USD_RETAIL,0.607665,0.607838,0.608145,0.608005,0.608362,0.608720,0.608510,0.608130
764,2020-03-18 20:30:00,0.56977,0.56492,0.56886,0.56580,5.10,AUD_UNEMP,0.577703,0.577822,0.578643,0.579238,0.579213,0.579850,0.578890,0.577830

0      0.995855
1      0.995855
2      0.995248
3      0.999523
4      0.999523
         ...
760    0.650190
761    0.643855
762    0.607665
763    0.607665
764    0.577703
Name: average_value_after_15_mins, Length: 765, dtype: float64