In [67]:
import pandas as pd

In [68]:
#IMPORT ALL THE FILES AND KEEP ONLY DESIRERED COLUMNS OF THE EVENT DATA

col = ['DATE','TIME','c','D','E','F','G','H','I','J']
drop_cols = ['c','D','E','F','G','I','J']

AUD_USD_df = pd.read_csv('AUDUSD-2000-2020-15m.csv') #AUS_USD CURRENCY DATA SET

AUD_GDP_df = pd.read_csv('AUD_GDP.csv',header = None,names = col,parse_dates= [[0,1]]) 
AUD_GDP_df = AUD_GDP_df.drop(columns=drop_cols)

AUD_PPI_df = pd.read_csv('AUD_PPI.csv',header = None,names = col,parse_dates= [[0,1]])
AUD_PPI_df = AUD_PPI_df.drop(columns=drop_cols)

AUD_RETAILSALES_df = pd.read_csv('AUD_RETAILSALES.csv',header = None,names = col,parse_dates= [[0,1]])
AUD_RETAILSALES_df = AUD_RETAILSALES_df.drop(columns=drop_cols)

AUD_UNEMP_df = pd.read_csv('AUD_UNEMP.csv',header = None,names = col,parse_dates= [[0,1]])
AUD_UNEMP_df = AUD_UNEMP_df.drop(columns=drop_cols)

AUD_CPI_df = pd.read_csv('AUD_CPI.csv',header = None,names = col,parse_dates= [[0,1]])
AUD_CPI_df = AUD_CPI_df.drop(columns=drop_cols)

USD_CPI_df = pd.read_csv('USD_CPI.csv',header = None,names = col,parse_dates= [[0,1]])
USD_CPI_df = USD_CPI_df.drop(columns=drop_cols)

USD_GDP_df = pd.read_csv('USD_GDP.csv',header = None,names = col,parse_dates= [[0,1]])
USD_GDP_df = USD_GDP_df.drop(columns=drop_cols)

USD_IR_df = pd.read_csv('USD_IR.csv',header = None,names = col,parse_dates= [[0,1]])
USD_IR_df = USD_IR_df.drop(columns=drop_cols)

USD_PAYROLL_df = pd.read_csv('USD_PAYROLL.csv',header = None,names = col,parse_dates= [[0,1]])
USD_PAYROLL_df = USD_PAYROLL_df.drop(columns=drop_cols)

USD_PPI_df = pd.read_csv('USD_PPI.csv',header = None,names = col,parse_dates= [[0,1]])
USD_PPI_df = USD_PPI_df.drop(columns=drop_cols)

USD_RETAIL_df = pd.read_csv('USD_RETAIL.csv',header = None,names = col,parse_dates= [[0,1]])
USD_RETAIL_df = USD_RETAIL_df.drop(columns=drop_cols)

USD_UNEMP_df = pd.read_csv('USD_UNEMP.csv',header = None,names = col,parse_dates= [[0,1]])
USD_UNEMP_df = USD_UNEMP_df.drop(columns=drop_cols)



 
AUD_GDP_df

             DATE_TIME    H
0  2011-03-01 19:30:00  0.7
1  2011-05-31 20:30:00 -1.2
2  2011-09-06 20:30:00  1.2
3  2011-12-06 19:30:00  1.0
4  2012-03-06 19:30:00  0.4
5  2012-06-05 20:30:00  1.3
6  2012-09-04 20:30:00  0.6
7  2012-12-04 19:30:00  0.5
8  2013-03-05 19:30:00  0.6
9  2013-06-04 20:30:00  0.6
10 2013-09-03 20:30:00  0.6
11 2013-12-03 19:30:00  0.6
12 2014-03-04 19:30:00  0.8
13 2014-06-03 20:30:00  1.1
14 2014-09-02 20:30:00  0.5
15 2014-12-02 19:30:00  0.3
16 2015-03-03 19:30:00  0.5
17 2015-06-02 20:30:00  0.9
18 2015-09-01 20:30:00  0.2
19 2015-12-01 19:30:00  0.9
20 2016-03-01 19:30:00  0.6
21 2016-05-31 20:30:00  1.1
22 2016-09-06 20:30:00  0.5
23 2016-12-06 19:30:00 -0.5
24 2017-02-28 19:30:00  1.1
25 2017-06-06 20:30:00  0.3
26 2017-09-05 20:30:00  0.8
27 2017-12-05 19:30:00  2.8
28 2018-03-06 20:30:00  0.4
29 2018-06-05 21:30:00  1.0
30 2018-09-04 21:30:00  0.9
31 2018-12-04 19:30:00  0.3
32 2019-03-05 20:30:00  0.2
33 2019-06-04 20:30:00  0.4
34 2019-09-03 20:30:00  0.5
35 2019-12-03 19:30:00  0.4
36 2020-03-03 20:30:00  0.5
37 2020-06-02 21:30:00 -0.3
38 2020-09-01 21:30:00 -7.0

In [69]:

 
df.merge(AUD_GDP_df, on = 'DATE_TIME', how = 'left', suffixes = ('','AUD_GDP'))

ValueError: You are trying to merge on object and datetime64[ns] columns. If you wish to proceed you should use pd.concat